name = "infliker-cms"
main = "src/index.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "infliker-cms-db"
database_id = "6d0c2aa4-899a-41a7-82f1-4af6a35e3973"

[env.production]
vars = { ENVIRONMENT = "production" }

[site]
bucket = "./public"
